### ISSUE TITLE
Handling microscopes at the project level

### ISSUE THREAD

**Issue by Rdornier** [BIOP/ArgoLight_analysis_tool#4]
The current implementation states that microscopes should live at the dataset level on OMERO (one dataset per microscope).
TODO : try to also allow microscopes to live at the project level on OMERO (the local hierarchy implementation should remain unchanged)

**Comment by Rdornier** [comment]
Seems to be feasible

In the GUI
- ask if the microscopes are living on dataset / project
- if living at dataset level, select the corresponding project in the project drop-down list and select the microscope to process in its corresponding drop-down list
- if living on at project level, select the microscope to process (will be the list of available project for the current log-in user) and them the dataset to process (i.e. acquisition date or something else)

In the code
- It implies to add 2 methods to list datasets and projects
- to load images from the selected dataset (may have a name mismatch between microscopeName and datasetName => have to figure out how to handle them differently when microscopes live at the project level)

**Comment by Rdornier** [comment]
Here is a snapshot version of the plugin, which includes reading the microscopes from the project level.
@lguerard If you want to give a try and to give feedback, feel free.

[argolight_analysis_tool-1.1.0-SNAPSHOT.zip](https://github.com/user-attachments/files/16176782/argolight_analysis_tool-1.1.0-SNAPSHOT.zip)

**Comment by Rdornier** [comment]
Fixing small bugs and enabling a disconnect button
[argolight_analysis_tool-1.1.0-SNAPSHOT.zip](https://github.com/user-attachments/files/16264246/argolight_analysis_tool-1.1.0-SNAPSHOT.zip)

**Comment by lguerard** [comment]
Thanks a lot for looking into it and finding a solution @Rdornier !!!

I'll test it ASAP and let you know !

**Comment by Rdornier** [comment]
Fixed in version 1.1.0.
